version: '3.4'
services:
  mongodb:
    image: mongo:latest
    ports:
    - 27017:27017

  minio:
    image: minio/minio:RELEASE.2020-05-08T02-40-49Z
    command: server /data
    ports:
      - 9000:9000
    volumes:
      - minio_data:/data

  image-resizer:
    image: image-resizer:${IMAGE_TAG}
    environment:
      APP_MONGO_URI: mongodb://mongodb:27017
      APP_MINIO_ENDPOINT: minio:9000
    depends_on:
      - minio
      - mongodb
    links:
      - minio
      - mongodb
    ports:
      - 8080:8080
      - 8888:8888
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/health"]
      interval: 5s
      timeout: 10s
      retries: 100
      start_period: 40s
    restart: always

volumes:
  minio_data:
    driver: local