// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Image struct {
	ID         string     `json:"id"`
	Path       string     `json:"path"`
	ClientName string     `json:"clientName"`
	MimeType   string     `json:"mimeType"`
	Size       int        `json:"size"`
	UploadAt   *time.Time `json:"uploadAt"`
	Sizes      []*Size    `json:"sizes"`
}

type Size struct {
	Path   string `json:"path"`
	Width  int    `json:"width"`
	Height int    `json:"height"`
}

type SizeInput struct {
	Width  int `json:"width"`
	Height int `json:"height"`
}
